#!/bin/bash

current_branch=$(git rev-parse --abbrev-ref HEAD)

main_branch="(main|master|dev|develop)"
if [[ $current_branch =~ $main_branch ]]; then
    echo -e "\033[1;31m[ERROR] Please don't commit directly to $current_branch.\033[0m";
    exit 1
fi

valid_branch_names="^(feature|bugfix|improvement|library|prerelease|hotfix)\/[a-z0-9._-]+$"
if [[ ! $current_branch =~ $valid_branch_names ]]; then
    echo -e "\033[1;31m[ERROR] Your branch name is illegal. Please rename your branch with using following regex: $valid_branch_names\033[0m"
    exit 1
fi

valid_commit="^(feat|fix|docs|style|refactor|perf|test|chore|build|ci)(.+?)?: .+"
if [[ ! $1 =~ $valid_commit ]]; then
   echo -e "\033[1;31m[ERROR] Your commit title did not follow semantic versioning.\033[0m"
    exit 1
fi

./mvnw clean validate
if [ "$?" -ne 0 ]; then
    echo -e "\033[1;31m[ERROR] Maven Validate unsuccessful.\033[0m"
    exit 1
fi

exit 0
